website:
  title: "Le Minh Phuong"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - text: "Curriculum Vitae"
        href: CV_PhuongLE.pdf
  page-navigation: true
  site-url: /

format:
  html:
    theme:
      light: minty
      dark: sketchy
    css: styles.css
    toc: true
