project:
  type: website
  output-dir: docs



website:
  title: "Le Minh Phuong"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Research.qmd
        text: Research
      - text: "Curriculum Vitae"
        href: cv/phuongcv.pdf
      
format:
  html:
    theme: 
      light: minty   # minty or flatly
      dark: sketchy   # slate
    css: styles.css
    toc: true

editor: visual



