<<<<<<< HEAD
project:
  type: website
  output-dir: docs

website:
  title: "Le Minh Phuong"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - text: "Curriculum Vitae"
        href: CV_PhuongLE.pdf

format:
  html:
    theme:
      light: minty   # minty or flatly
      dark: sketchy  # slate
    css: styles.css
    toc: true

editor: visual
=======
project:
  type: website
  output-dir: docs



website:
  title: "Le Minh Phuong"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - text: "Curriculum Vitae"
        href: CV_PhuongLE.pdf
      
format:
  html:
    theme: 
      light: minty   # minty or flatly
      dark: sketchy   # slate
    css: styles.css
    toc: true

editor: visual



>>>>>>> 5b4a1df99f5f72f174348b2c207169b2546eb888
