# About me

I am a Vietnamese fourth year PhD student in development economics at the [Université Paris-1 Panthéon-Sorbonne](https://www.pantheonsorbonne.fr/page-perso/mple), under the supervision of Mohamed Ali Marouani ; and a part-time Attaché Temporaire d'Enseignement et de Recherche (ATER) at [IEDES](https://iedes.pantheonsorbonne.fr/liedes-en-bref) (Paris-1).\
\
My research interests lie in the areas of inequality, crises, and firms productivity. I am passionate about understanding the economic dynamics that shape the livelihoods of individuals and communities, and strive to contribute to the development of policies that foster inclusive growth and reduce poverty.

Through my research, I aim to generate new insights and knowledge that can inform policy-making and improve the well-being of people in developing countries. Thank you for visiting my page and I hope you find my research and experiences informative

# Research Interests

-   Inequality

-   Crises (Covid, Tunisian Revolution)

-   Firms' productivity

# Education

**Panthéon-Sorbonne University**                            Paris, France  \
PhD in Economics                                                    2019 -  \
Advisor: Mohamed Ali Marouani

Dissertation : "*Exploring the Interplay of Productivity and Inequality in times of Crises: The Cases of Tunisia and Vietnam*"

**Panthéon-Sorbonne University**                            Paris, France  \
Master 2                                                                  2016 - 2017  \
