## Publications

- **Minh-Phuong Le**, Lisa Chauvet, Mohamed Ali Marouani (2024). "*The Great Lockdown and the Small Busi-ness: How did the Covid-19 crisis affect Tunisian SMEs?*". World Development (Vol. 182). Article 106673. ([Link](https://doi.org/10.1016/j.worlddev.2024.106673))

- **Le, M.-P.**, Marouani, M.A., Marshalian, M. (2023). "*Tunisia: employment and inequality trends*", in Gradín, C. , Lewandowski, P. , Schotte, S. , Sen, K. (Eds.)(2023) Tasks, Skills, and Institutions: The Changing Nature of Work and Inequality. Oxford University Press. WIDER Studies in Development Economics. ([Link](10.1093/oso/9780192872241.001.0001))

-**LE Phuong Minh**, MAROUANI Mohamed Ali. (2021). "*Le fardeau des travailleurs vulnérables dans les pays en développement: une évaluation des effets du confinement en Tunisie*", Revue d'économie du déve-loppement, (Vol. 29), p. 85-110. DOI: 10.3917/edd.351.0085. ([Link](https://www.cairn.info/revue-d-economie-du-developpement-2021-1-page-85.htm))

## Working papers

-   Mohamed Ali Marouani, **Minh-Phuong Le** and Nidhal Ben Cheikh. "*Do Social Protection Programs Improve Health Related Outcomes of the Poor in Tunisia ?*", ERF Working Papers Series. ([Link](https://erf.org.eg/app/uploads/2022/09/1663594556_997_445362_1579.pdf))

-   Mohamed Ali Marouani, **Minh-Phuong Le** and M Marshalian. "*Jobs, earnings, and routine-task occupational change in times of revolution: the Tunisian perspective"*, WIDER Working Paper 2020/171. ([Link](https://policycommons.net/artifacts/1908950/wider-working-paper-2020171-jobs-earnings-and-routine-task-occupational-change-in-times-of-revolution/2660126/))

- Marouani, M. A., & **Le, M. P.** (2020). “The first victims of Covid-19 in developing countries? The most vul-nerable workers to the lockdown of the Tunisian economy”. GLO Discussion Paper No. 581. ([Link](https://ideas.repec.org/p/zbw/glodps/581.html))
