## Publications

-   Minh-Phuong Le, Lisa Chauvet and Mohamed Ali Marouani (2024). "*The Great Lockdown and the Small Business: How did the Covid-19 crisis affect Tunisian SMEs?*". World Development (Vol. 182). Article 106673. ([Link](https://doi.org/10.1016/j.worlddev.2024.106673))

-   Minh-Phuong Le, Mohamed Ali Marouani & Michelle Marshalian (2023). "*Tunisia: employment and inequality trends*", in Gradín, C. , Lewandowski, P. , Schotte, S. , Sen, K. (Eds.)(2023) Tasks, Skills, and Institutions: The Changing Nature of Work and Inequality. Oxford University Press. WIDER Studies in Development Economics. ([Link](10.1093/oso/9780192872241.001.0001))

-   Mohamed Ali Marouani, Minh-Phuong Le & Nidhal Ben Cheikh (2022). *"Do Social Protection Programs Improve Health Related Outcomes of the Poor in Tunisia?*" *Economic Research Forum Working Papers* (No. 1579). ([Link](https://erf.org.eg/app/uploads/2022/09/1663594556_997_445362_1579.pdf))

-   Minh-Phuong Le & Mohamed Ali Marouani (2021). "*Le fardeau des travailleurs vulnérables dans les pays en développement: une évaluation des effets du confinement en Tunisie*", Revue d'économie du développement, (Vol. 29), p. 85-110. DOI: 10.3917/edd.351.0085. ([Link](https://www.cairn.info/revue-d-economie-du-developpement-2021-1-page-85.htm))

-   Thi-Minh-Phuong Nguyen, Minh-Phuong Le, Thi-Tram Nguyen & Thi-Lan-Anh Tran (2016). Assessing the Impacts of Tariff Commitments of Trans-Pacific Partnership Agreement on Vietnam Fisheries sector. *VNU Journal of Science: Economics and Business* Vol. 32, No. 5E.

## **Works in progress**

-   Federica Alfani, Esther Delesalle, Minh-Phuong Le & Mohamed Ali Marouani. "*Forced to migrate in a warming world: Labor migration responses to drought-induced shocks in Tunisia.*"

-   Jean-Baptiste Guiffard & Minh-Phuong Le. "*Measuring AI substitutability and complementarity in developing countries' labor markets: Evidence from online job postings data.*"

## **Conferences**

-   Federica Alfani, Esther Delesalle, Minh-Phuong Le & Mohamed Ali Marouani. "Agricultural and migration responses to drought-induced shocks in Tunisia" (2025). ERF 31st Annual Conference: Youth, Demographic Dividend, Migration, Economic Challenges & Opportunities in MENA.

-   Minh-Phuong Le, Lisa Chauvet & Mohamed Ali Marouani (2023). "The Great Lockdown and the Small Business: How did the Covid-19 crisis affect Tunisian SMEs ?". ERF 29th Annual Conference: The Future of MENA Development Path: Risks and Opportunities in an Emerging World Order, Egypt.

-   Mohamed Ali Marouani & Minh-Phuong Le (2023). "The Dynamics of Earnings Inequality in Revolution Times". ERF 29th Annual Conference: The Future of MENA Development Path: Risks and Opportunities in an Emerging World Order, Egypt.

-   Minh-Phuong Le, Lisa Chauvet & Mohamed Ali Marouani (2023). "The Great Lockdown and the Small Business: How did the Covid-19 crisis affect Tunisian SMEs?" Journées Doctorales du Développement de l'AFEDEV, France.

-   Mohamed Ali Marouani, Minh-Phuong Le & Nidhal Ben Cheikh (2022). "Do Social Protection Programs Improve Health Related Outcomes of the Poor in Tunisia?" ERF's Policy Conference on "The Social Protection System in Tunisia", Tunisie.

-   Mohamed Ali Marouani & Minh-Phuong Le (2022). "The Role of Public Employment and Wage Policy in the Dynamic of Earnings Inequality: The Tunisian perspective". UNU-WIDER Development Conference "Reducing inequality -- the great challenge of our time", Columbia.

-   Mohamed Ali Marouani, Minh-Phuong Le, Michelle Marshalian (2020). "Jobs, earnings, and routine-task occupational change in times of Revolution: The Tunisian perspective". 3rd Annual IZA/World Bank/NJD/UNU-WIDER Jobs and Development Conference "Better Jobs for Development", Online.
